Final claw position
leejohnlee/botball-0329 pull request #3
Opened 2024-03-11 01:34 UTC by Oboy-Github

Lowered the final drop for the multipliers
Set the final claw position

2024-03-12 02:22 UTC, leejohnlee commented on create3/main.c
> +    for
Is this unfinished loop? Is it code that needs to be deleted but wasn't fully removed? Did this compile correctly before committing? Please review and fix.

2024-03-12 02:55 UTC, leejohnlee commented on create3/main.c
>  //inverse is 2048-value
Is this comment relevant to this function?

Is there a reason for subtracting 1 before doing the conversion, what happens if we want to move 1 inch?
Also, a good practice is to put any sort of conversion like this in it's own function entirely in case it's ever used anywhere else.

2024-03-12 02:56 UTC, leejohnlee commented on create3/main.c
> +}
Please use our convention of spacing functions by adding an empty line between them

2024-03-12 03:00 UTC, leejohnlee requested changes
Please review comments. We can go over it at the beginning of next meeting.

2024-03-12 05:59 UTC, Oboy-Github commented on create3/main.c
> +    for
Yes, I think it's an unfinished loop so we can remove it for now.

2024-03-12 06:00 UTC, Oboy-Github commented on create3/main.c
>  //inverse is 2048-value
I think Rocky wrote that down so maybe he knows...

2024-03-12 06:00 UTC, Oboy-Github commented on create3/main.c
> +}
Okay, I will make that change in the next meeting.

2024-03-18 03:13 UTC, closed without merging

2024-03-18 03:14 UTC, leejohnlee commented
Fixed issues and included same changes in subsequent commit